### ISSUE TITLE
Alert rather than write on game full

### ISSUE THREAD

**Issue by dylantientcheu** [lamapgame/lamap-bot#72]

**Comment by elhmn** [comment]
Are these closed issues linked to any pull request ?

**Comment by blurdylan** [comment]
Nope, those were the times where i was single handedly managing the repository. I used to push to master and open and close issues randomly. Now i try to follow a normal way.

**Comment by elhmn** [comment]
Awesome, so I guess the 3 remaining issues will be linked to actual PRs 🙇‍♂️

**Comment by blurdylan** [comment]
Yup. Will be merging one tonight.
